### PR TITLE
move devel module to require-dev

### PR DESCRIPTION
**Pull request by aekong**
make devel a dev dependency

### CODE REVIEW

**Comment by jszwedko** [comment]
(to be clear, I'm more than happy to see them kept up-to-date)

**Comment by aekong** [comment]
@jszwedko i did, it was, and i think it's ok (i hope).  any objections? @henryjiang-sfgov @josh-chou @hshaosf

**Comment by jszwedko** [comment]
I'm all about it.

**Comment by aekong** [comment]
#176 updated composer.lock as well, which was merged to master.  merged master to this branch, so all should be 👍 (hopefully)

**Pull request merged**
