### PR TITLE
[SG-1430] Do not carry over translations when cloning node

### PR DESCRIPTION
**Pull request by bookworm2000**
Apply patch from issue 3049127 for the Quick Node Clone project:
https://www.drupal.org/project/quick_node_clone/issues/3049127

This patch removes translations when in the process of cloning a node so that the new node created does not contain all the translation content.

### CODE REVIEW

**Review by arlina-espinoza — DISMISSED** [review]
Good catch @bookworm2000, thanks!

**Comment by bookworm2000** [comment]
@arlina-espinoza I had to rebase this one from develop since there were merge conflicts.  Not sure if I should make any changes to composer.lock now that I look at the one on the develop branch and don't see patches applied, but that is how I have always handled patches.

**Review by arlina-espinoza — CHANGES_REQUESTED** [review]
The `patches_applied` key has to do with the version of composer used, just to be sure @bookworm2000 can you run a `composer update nothing` on the project and recommit the composer.lock file so that the key shows up on the other packages that were patched, please?

**Comment by bookworm2000** [comment]
@arlina-espinoza Ran `composer update nothing` , committed changes, and pushed.  Didn't know that command existed!

**Comment by aekong** [comment]
> @arlina-espinoza Ran `composer update nothing` , committed changes, and pushed. Didn't know that command existed!

me neither!

**Review by aekong — APPROVED** [review]

**Review by arlina-espinoza — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
