### PR TITLE
update drupal core to 8.9.16

### PR DESCRIPTION
**Pull request by aekong**
https://www.drupal.org/sa-core-2021-003

### CODE REVIEW

**Comment by zakiya** [comment]
The build failed for what looks like Pantheon reasons. When I did this update for another client I lost classes on the form tag. I'm not sure if the update caused it but when the build is successful it'd be good to check for visual regressions on Drupal forms using the sfgovpl theme.

**Comment by aekong** [comment]
oof, thanks for the heads up!

**Comment by aekong** [comment]
tried re-running the build and getting a failure during terminus drush updatedb:
```
Drupal\Core\DependencyInjection\ContainerNotInitializedException:    [error]
\Drupal::$container is not initialized yet. \Drupal::setContainer()
must be called with a real container. in
/code/web/core/lib/Drupal.php:130
Stack trace:
#0 /code/web/core/lib/Drupal.php(158): Drupal::getContainer()
#1 /code/web/core/includes/install.inc(84):
Drupal::service('extension.list....')
#2 /code/vendor/drush/drush/commands/core/drupal/update.inc(135):
drupal_load_updates()
#3 /code/vendor/drush/drush/commands/core/core.drush.inc(466):
update_main()
#4 /code/vendor/drush/drush/includes/command.inc(422):
drush_core_updatedb()
#5 /code/vendor/drush/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#6 /code/vendor/drush/drush/includes/command.inc(199):
drush_command()
#7 /code/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#8 /code/vendor/drush/drush/includes/preflight.inc(67):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#9 /code/vendor/drush/drush/drush.php(12): drush_main()
#10 {main}
 [notice] Command: *****.pr-914 -- drush updatedb [Exit: 1]
 [error]   

Exited with code exit status 1
CircleCI received exit code 1
```
no issues for myself running lando drush updb locally, so wondering if it's a pantheon thing

**Comment by aekong** [comment]
@zakiya i updated to drush 10 per a chat in pantheon's slack with https://github.com/greg-1-anderson.  do you think you could pull this down and just verify that you don't have any issues running drush commands (updb, cim, cr)?

thanks!

**Review by zakiya — APPROVED** [review]

**Review by zakiya — APPROVED** [review]

**Pull request merged**
